SG-21170 [ZD to AKN] Update links referenced from code to the old support site to point to AKN
shotgunsoftware/tk-framework-adminui pull request #32
Opened 2021-11-02 21:31 UTC by 000paradox000

This PR replaces ZD urls to AKN and developer urls

2021-11-08 16:11 UTC, mathurf requested changes
Need to fix one of the URL. It is pointing to a 404 page

2021-11-08 16:11 UTC, mathurf commented on python/ui/setup_project.py
> +        self.storage_def_lbl.setText(QtGui.QApplication.translate("Wizard", "This configuration requires one or more filesystem roots where files will be stored. For each filesystem root required by
That URL bring me to a 404 page :/

2021-11-08 23:27 UTC, 000paradox000 commented on python/ui/setup_project.py
> +        self.storage_def_lbl.setText(QtGui.QApplication.translate("Wizard", "This configuration requires one or more filesystem roots where files will be stored. For each filesystem root required by
Done

2021-11-09 13:54 UTC, mathurf requested changes

2021-11-09 13:54 UTC, mathurf commented on python/ui/setup_project.py
> +        self.storage_def_lbl.setText(QtGui.QApplication.translate("Wizard", "This configuration requires one or more filesystem roots where files will be stored. For each filesystem root required by
I think https://help.autodesk.com/view/SGSUB/ENU/?guid#how-do-i-set-up-local-file-storage-for-networked-resources-such-as-a-shared-element-library-\
should be https://help.autodesk.com/view/SGSUB/ENU/?guid=SG_Administrator_ar_data_management_ar_linking_local_files_html

2021-11-09 18:47 UTC, mathurf approved these changes
LGTM!

2021-11-09 18:48 UTC, merged