SG-24400 remove default config from the advanced setup
shotgunsoftware/tk-framework-adminui pull request #33
Opened 2021-11-05 15:26 UTC by NorberMV

Removed the "default_config_page.py" and enabled by default the "tk-config-default2" configuration.

2021-11-05 15:43 UTC, 000paradox000 requested changes

2021-11-05 15:43 UTC, 000paradox000 commented on python/setup_project/setup_type_page.py
> +        if (selection == 0) and self._storage_map_page_id is not None:
Have you consider removing ( ) in this line?

2021-11-05 15:43 UTC, 000paradox000 commented on python/setup_project/setup_type_page.py
>          if (selection == 1) and self._project_page_id is not None:
Same note here

2021-11-05 15:43 UTC, 000paradox000 commented on python/setup_project/setup_type_page.py
>          elif (selection == 2) and self._github_page_id is not None:
Same note here

2021-11-09 13:50 UTC, jfboismenu requested changes

2021-11-09 13:50 UTC, jfboismenu commented on python/ui/setup_project.py
> -        self.default_configs_page = DefaultConfigPage()
This change should be accompanied with an update to the resources folder. [setup_project.py is auto-generated](https://github.com/shotgunsoftware/tk-framework-adminui/blob/master/resources/build_resources.sh#L42).

2021-11-11 20:53 UTC, mathurf approved these changes
LGTM!

Tested it locally and all issues found are now fixed.
Ready to merge if Ariel is fine with the code. :) 

Great work!

2021-11-11 21:05 UTC, 000paradox000 approved these changes
LGTM very good job

2021-11-11 21:09 UTC, merged